# Generated by Django 4.0 on 2022-02-13 16:28

from django.db import migrations, models
import django.db.models.deletion
import main.dataValidator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('month', models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], max_length=20)),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('validorCommentary', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Refusé', 'Refusé'), ('Accepté', 'Accepté')], max_length=20)),
                ('nature', models.CharField(choices=[('Essence', 'Carburant'), ('Hebergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ('Demande d avance', 'Demande d avance')], max_length=20)),
                ('amountHT', models.FloatField()),
                ('amountTVA', models.FloatField()),
                ('proof', models.FileField(upload_to='proofs', validators=[main.dataValidator.validate_file_type])),
                ('expenseReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.expensereport')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MileageExpense',
            fields=[
                ('refundrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.refundrequest')),
                ('carFiscalPower', models.CharField(choices=[('3 cv et moins', '3 cv et moins'), ('4 cv', '4 cv'), ('5 cv', '5 cv'), ('6 cv', '6 cv'), ('7 cv et plus', '7 cv et plus')], default='3 cv et moins', max_length=20)),
                ('endCity', models.CharField(default='', max_length=100)),
                ('distance', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.refundrequest',),
        ),
        migrations.AddField(
            model_name='mission',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mService', to='main.service'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='departmentHead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cDeptHead', to='main.service'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cValidator', to='main.collaborator'),
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('validorCommentary', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Refusé', 'Refusé'), ('Accepté', 'Accepté')], max_length=20)),
                ('nature', models.CharField(choices=[('Essence', 'Carburant'), ('Hebergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ('Demande d avance', 'Demande d avance')], max_length=20)),
                ('estimatedPrice', models.FloatField()),
                ('advanceCommentary', models.CharField(max_length=1000)),
                ('expenseReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.expensereport')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissionCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountAdvance', models.FloatField(default=0)),
                ('idCollab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcCollab', to='main.collaborator')),
                ('idMission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcMission', to='main.mission')),
            ],
            options={
                'unique_together': {('idMission', 'idCollab')},
            },
        ),
    ]
