# Generated by Django 4.0.1 on 2022-01-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('isvalidator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nae', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amountHT', models.FloatField()),
                ('amountTVA', models.FloatField()),
                ('advance', models.BooleanField(default=False)),
                ('proof', models.FileField(upload_to='proofs')),
                ('commentary', models.CharField(max_length=1000)),
                ('validated', models.BooleanField(null=True)),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elCollaborator', to='main.collaborator')),
                ('expenseReport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.expensereport')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mission')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elValidator', to='main.collaborator')),
            ],
        ),
        migrations.AddField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cValidator', to='main.collaborator'),
        ),
    ]
