# Generated by Django 4.0 on 2022-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='validorCommentary',
            field=models.CharField(default='dfghjk', max_length=1000),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='validorCommentary',
            field=models.CharField(default='dfghjk', max_length=1000),
        ),
    ]
