# Generated by Django 4.0.1 on 2022-01-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_nae_mission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='login',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='password',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
