# Generated by Django 4.0.1 on 2022-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_collaborator_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='month',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Fevrier', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
