# Generated by Django 4.0 on 2022-01-16 14:26

from django.db import migrations, models
import main.dataValidator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_collaborator_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='proof',
            field=models.FileField(upload_to='proofs', validators=[main.dataValidator.validate_file_type]),
        ),
    ]
