# Generated by Django 4.0 on 2022-01-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expenseline_proof'),
        ('main', '0004_expensereport_month'),
    ]

    operations = [
    ]
