# Generated by Django 4.0 on 2022-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_advance_validorcommentary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='validorCommentary',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='validorCommentary',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
