# Generated by Django 4.0 on 2022-01-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20220116_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='proof',
            field=models.FileField(upload_to='proofs'),
        ),
    ]
