# Generated by Django 4.0 on 2022-02-16 11:18

from django.db import migrations, models
import main.dataValidator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mileageexpense_startcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs', validators=[main.dataValidator.validate_file_type]),
        ),
    ]
