# Generated by Django 4.0 on 2022-02-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_refundrequest_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='month',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Aout', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Decembre', 'Decembre')], max_length=20),
        ),
    ]
