# Generated by Django 4.0 on 2022-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_expenseline_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
