# Generated by Django 4.0.1 on 2022-02-01 13:50

from django.db import migrations, models
import django.utils.timezone
import main.dataValidator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_expenseline_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='carFiscalPower',
            field=models.CharField(choices=[('3 cv et moins', '3 cv et moins'), ('4 cv', '4 cv'), ('5 cv', '5 cv'), ('6 cv', '6 cv'), ('7 cv et plus', '7 cv et plus')], default='5 cv', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='carRegistrationDocument',
            field=models.FileField(default='', upload_to='proofs', validators=[main.dataValidator.validate_file_type]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseline',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expenseline',
            name='endCity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='montantAvance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='nature',
            field=models.CharField(choices=[('Essence', 'Carburant'), ('Hebergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ('Demande d avance', 'Demande d avance')], max_length=20),
        ),
    ]
