# Generated by Django 4.0.1 on 2022-02-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_collaborator_carfiscalpower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='isvalidator',
            new_name='isValidator',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='montantAvance',
            new_name='amountAdvance',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='validator',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='departmentHead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cDeptHead', to='main.service'),
        ),
    ]
