# Generated by Django 4.0 on 2022-02-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_isvalidator_collaborator_isvalidator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='nature',
            field=models.CharField(choices=[('Essence', 'Carburant'), ('Hébergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ("Demande d'avance", 'Demande d avance')], max_length=20),
        ),
    ]
