# Generated by Django 4.0.1 on 2022-02-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_date_mission_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('expenseline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expenseline')),
                ('estimatedPrice', models.FloatField()),
                ('advanceCommentary', models.CharField(max_length=1000)),
            ],
            bases=('main.expenseline',),
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='amountHT',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='amountTVA',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='endCity',
        ),
        migrations.RemoveField(
            model_name='expenseline',
            name='proof',
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('expenseline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.expenseline')),
                ('amountHT', models.FloatField()),
                ('amountTVA', models.FloatField()),
            ],
            bases=('main.expenseline',),
        ),
        migrations.CreateModel(
            name='MileageExpense',
            fields=[
                ('refundrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.refundrequest')),
                ('carFiscalPower', models.CharField(choices=[('3 cv et moins', '3 cv et moins'), ('4 cv', '4 cv'), ('5 cv', '5 cv'), ('6 cv', '6 cv'), ('7 cv et plus', '7 cv et plus')], max_length=20)),
                ('endCity', models.CharField(default='', max_length=100)),
                ('distance', models.FloatField(default=0)),
            ],
            bases=('main.refundrequest',),
        ),
    ]
