# Generated by Django 4.0.1 on 2022-02-11 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.dataValidator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_advance_remove_expenseline_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='expenseline_ptr',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='carFiscalPower',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='carRegistrationDocument',
        ),
        migrations.RemoveField(
            model_name='refundrequest',
            name='expenseline_ptr',
        ),
        migrations.AddField(
            model_name='advance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='expenseReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.expensereport'),
        ),
        migrations.AddField(
            model_name='advance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mission'),
        ),
        migrations.AddField(
            model_name='advance',
            name='nature',
            field=models.CharField(choices=[('Essence', 'Carburant'), ('Hebergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ('Demande d avance', 'Demande d avance')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='state',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Refusé', 'Refusé'), ('Accepté', 'Accepté')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advance',
            name='validorCommentary',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='expenseReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.expensereport'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mission'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='nature',
            field=models.CharField(choices=[('Essence', 'Carburant'), ('Hebergement', 'Hebergement'), ('Repas', 'Repas'), ('Transport', 'Transport'), ('Voyage', 'Voyage'), ('Autre', 'Autre'), ('Achat', 'Achat'), ('Demande d avance', 'Demande d avance')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='proof',
            field=models.FileField(default='', upload_to='proofs', validators=[main.dataValidator.validate_file_type]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='state',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Refusé', 'Refusé'), ('Accepté', 'Accepté')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='validorCommentary',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpenseLine',
        ),
    ]
